[package]
name = "llama-cpp-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llama-cpp-sys-2 = { path = "../llama-cpp-sys-2", version = "0.1.0" }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
hf-hub = { workspace = true }
criterion = { workspace = true }
pprof = { workspace = true, features = ["criterion", "flamegraph"] }

[[bench]]
name = "grammar_bias"
harness = false

[features]
cublas = ["llama-cpp-sys-2/cublas"]

[lints]
workspace = true