name: Llama Cpp Rs Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  check:
    name: Run Tests on LLama Cpp Rs
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup protoc
        uses: arduino/setup-protoc@v2.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Compile Deps
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo apt-get update && sudo apt-get install -y build-essential curl libssl-dev libclang-dev pkg-config cmake git
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Clippy
        run: cargo clippy
      - name: Clippy
        run: cargo fmt
