name: Llama Cpp Rs Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  check:
    name: Run Tests on LLama Cpp Rs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Compile Deps
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo apt-get update && sudo apt-get install -y build-essential curl libssl-dev libclang-dev pkg-config cmake git
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Clippy
        run: cargo clippy
      - name: Fmt
        run: cargo fmt
      - name: Test
        run: cargo test