name: Test Publish to Crates.io

on:
  release:
    types:
      - created
    workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Publish crates for llama-cpp-2
        uses: katyo/publish-crates@v2
        with:
          path: './llama-cpp-2'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          args: --no-verify
          dry-run: true

      - name: Publish crates for llama-cpp-sys-2
        uses: katyo/publish-crates@v2
        with:
          path: './llama-cpp-sys-2'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          args: --no-verify
          dry-run: true
