name: Test Publish to Crates.io

on:
  release:
    types:
      - created
    workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Dry-run publish to Crates.io (for llama-cpp-2)
        run: cargo release --dry-run
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Dry-run publish to Crates.io (for llama-cpp-sys-2)
        run: cd llama-cpp-sys-2 && cargo release --dry-run
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
