name: Update llama cpp nightly
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  pull-requests: write
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update llama cpp
    steps:
      - uses: actions/checkout@v3
        name: Checkout latest
        with:
          submodules: recursive
      - name: create branch
        run: git checkout -b update-llama-cpp-$(date -I)
      - name: update submodules
        run: git submodule update --remote
      - name: config git
        run: |
          git config --global user.email "marcus@utilityai.ca"
          git config --global user.name "Marcus Dunn"
      - name: commit
        run: git commit -am "updated llama.cpp"
      - name: push
        run: git push --set-upstream origin update-llama-cpp-$(date -I)
      - name: create pr
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh pr create --fill